[package]
name = "whatthegif_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.25.2"
tungstenite = "0.16.0"
tokio-tungstenite = "0.16.1"
